---
# yum is packaged with its python binding

- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - shell: dnf -y remove python2-dnf
      args:
        warn: false
      when: ansible_distribution == 'Fedora'

    - shell: apt-get -y remove python-apt
      args:
        warn: false
      when: ansible_distribution == 'Ubuntu'
